// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrzepnwtzbqjidnoindt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlyemVwbnd0emJxamlkbm9pbmR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MTY4MTUsImV4cCI6MjA3MjQ5MjgxNX0.TC8PNSZQf7NGPAwkOfsIFCbGAKtcZE0O6cHsxBJLvpA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});